---
roles:
  - name: pihole
    src: https://github.com/Forinil/ansible-pihole
  - name: tailscale
    src: https://github.com/artis3n/ansible-role-tailscale

collections:
  - name: ansible.posix
  - name: community.general
