---
- name: Provision Pi-hole server
  hosts: '{{ target_hosts }}'
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  vars_prompt:
    - name: target_hosts
      prompt: "Please specify hosts to run playbook on"
      private: false
    - name: admin_user
      prompt: "Please specify the name of the admin user to be created"
      private: false
    - name: admin_password
      prompt: "Please specify the password of the admin user to be created"
      private: true
    - name: admin_ssh_key
      prompt: "Please specify the location of the admin's SSH key"
      private: false
    - name: pihole_password
      prompt: "Please specify the Pi-hole web GUI password"
      private: true
    - name: tailscale_network_domain
      prompt: "Please specify Tailscale network domain"
      private: false
    - name: tailscale_key
      prompt: "Please specify Tailscale authentication key"
      private: true
  vars_files:
    - vars/pihole-config.yml
  tasks:
    - name: Apply system settings
      ansible.builtin.import_tasks:
        file: tasks/system-settings.yml
    - name: Create users and groups
      ansible.builtin.import_tasks:
        file: tasks/users-and-groups.yml
    - name: Install and configure Cloudflare DNS proxy
      ansible.builtin.import_tasks:
        file: tasks/configure-cloudflared-dns-proxy.yml
    - name: Install and configure Tailscale
      ansible.builtin.import_tasks:
        file: tasks/configure-tailscale.yml
    - name: Install and configure Pi-hole
      ansible.builtin.import_tasks:
        file: tasks/configure-pihole.yml
