---
- name: Create /etc/dnsmasq.d directory
  ansible.builtin.file:
    path: /etc/dnsmasq.d
    state: directory
    mode: '0755'

- name: Create /etc/dnsmasq.d/02-cobia-hydra.ts.net.conf file
  template:
    src: "./templates/02-cobia-hydra.ts.net.conf.j2"
    dest: "/etc/dnsmasq.d/02-cobia-hydra.ts.net.conf"
    owner: root
    group: root
    mode: 0644

- name: Install Pi-hole
  include_role:
    name: pihole

- name: Change permission of /etc/pihole directory
  ansible.builtin.file:
    path: /etc/pihole
    state: directory
    mode: '0777'

- name: Change permission of /etc/pihole/pihole-FTL.db file
  ansible.builtin.file:
    path: /etc/pihole/pihole-FTL.db
    state: file
    mode: '0666'

- name: Configure git user email
  git_config:
    name: user.email
    scope: global
    value: 'kbotor@gmail.com'

- name: Configure git user name
  git_config:
    name: user.name
    scope: global
    value: 'Konrad Botor'

- name: Install pihole-cloudsync
  ansible.builtin.git:
    repo: 'https://github.com/stevejenkins/pihole-cloudsync.git'
    dest: /usr/local/bin/pihole-cloudsync
    version: master
    accept_newhostkey: true

- name: Clone Pi-hole configuration repository
  ansible.builtin.git:
    repo: git@github.com:Forinil/pihole-config.git
    dest: /usr/local/bin/my-pihole-lists
    version: "{{ pihole_config_branch }}"
    accept_newhostkey: true