---
- name: Create group '{{  admin_user }}'
  ansible.builtin.group:
    name: "{{  admin_user }}"
    state: present

- name: Ensure group 'cloudflared' exists
  ansible.builtin.group:
    name: cloudflared
    state: present

- name: Create user '{{  admin_user }}'
  ansible.builtin.user:
    name: "{{  admin_user }}"
    group: "{{  admin_user }}"
    groups: users,adm,dialout,audio,video,plugdev,cdrom,games,input,render,sudo
    shell: /bin/bash
    home: "{{ '/home/' + admin_user }}"
    password: "{{ admin_password | ansible.builtin.password_hash }}"
    password_lock: false

- name: Create user 'cloudflared'
  ansible.builtin.user:
    name: cloudflared
    group: cloudflared
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: Set authorized key for user '{{  admin_user }}'
  ansible.posix.authorized_key:
    user: "{{  admin_user }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Copy id_rsa for user '{{  admin_user }}'
  ansible.builtin.copy:
    src: "{{ admin_ssh_key }}"
    dest: "{{ '/home/' + admin_user + '/.ssh/id_rsa' }}"
    owner: "{{  admin_user }}"
    group: "{{  admin_user }}"
    mode: '0600'

- name: Copy id_rsa for user root
  ansible.builtin.copy:
    src: "{{ admin_ssh_key }}"
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: '0600'
