name: Ansible Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint playbooks
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Lint cloudflared playbook
        uses: ansible/ansible-lint@v25.1.0
        with:
          # args: ""
          # setup_python: "true"
          working_directory: "cloudflared"
          # requirements_file: "requirements.yml"
      # - name: Lint pihole playbook
      #   uses: ansible/ansible-lint@v25.1.0
      #   with:
      #     # args: ""
      #     # setup_python: "true"
      #     working_directory: "pihole"
      #     requirements_file: "requirements.yml"
      - name: Lint proxmox-ve-service-checker playbook
        uses: ansible/ansible-lint@v25.1.0
        with:
          # args: ""
          # setup_python: "true"
          working_directory: "proxmox-ve/service-checker"
          # requirements_file: "requirements.yml"
      - name: Lint proxmox-ve-gui-sensors-mod playbook
        uses: ansible/ansible-lint@v25.1.0
        with:
          # args: ""
          # setup_python: "true"
          working_directory: "proxmox-ve/gui-sensors-mod"
          # requirements_file: "requirements.yml"