name: Ansible Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3.5.2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@v6.16.0